<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Admin | <?=$title?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Google Fonts
     ============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
       ============================================ -->
    <link rel="stylesheet" href="/admin/css/bootstrap.min.css">

    <!-- Bootstrap CSS
		============================================ -->
    <!-- Data Table JS
            ============================================ -->
    <link rel="stylesheet" href="/admin/css/jquery.dataTables.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" type="text/css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css">

    <link rel="stylesheet" href="/admin/css/preloader.css">

    <link rel="stylesheet" href="/admin/css/dropzone/dropzone.css">

    <link rel="stylesheet" href="/admin/css/notika-custom-icon.css">

    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="/admin/css/main.css">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="/admin/style.css">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="/admin/css/responsive.css">
    <!-- modernizr JS
		============================================ -->
    <script src="/admin/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<!-- Start Header Top Area -->
<div class="header-top-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="logo-area">
                    <a href="/"><h1 style="height: 34px; width:100px; color: white;">MTC</h1></a>
                </div>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="header-top-menu">
                    <ul class="nav navbar-nav notika-top-nav">
                        <li class="nav-item"><span  style="font-size: 15px;" class="aty-link"><i>Welcome, Admin</i></span></li>
                        <li class="nav-item"><a href="#" data-toggle="dropdown" role="button" class="nav-link" href="/"><span><i class="fa fa-sign-out-alt"></i></span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- End Header Top Area -->

<?=$content?>

<!-- Start Footer area-->
<div class="footer-copyright-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="footer-copy-right">
                    <p><span id="copy-right"> © Copyright MTC <?= date('Y')?> </span> <a href="/" class="footerLinks"></a>

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Footer area-->
<!-- jquery
    ============================================ -->
<script src="/admin/js/vendor/jquery-1.12.4.min.js"></script>
<!-- bootstrap JS
    ============================================ -->
<script src="/admin/js/bootstrap.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script src="/admin/js/sweetalert.min.js"></script>
<script src="/admin/js/dropzone/dropzone.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/parsley.js/2.9.1/parsley.js"></script>

<script src="/admin/js/jquery.preloader.js"></script>

<script src="/admin/js/data-table/jquery.dataTables.min.js"></script>
<script src="/admin/js/data-table/data-table-act.js"></script>

<script src="/admin/js/custom/property.js"></script>

</body>

</html>